metc(){
    max_threads=$1
    if [ ! "$thread_ctrl_n" ];then
    thread_ctrl_n=0
    fi
    let thread_ctrl_n+=1
    if [ "$thread_ctrl_n" -eq "$max_threads" ];then
    wait
    thread_ctrl_n=0
    fi
}
memkdir(){
    for path in $@
    do
    test -d $path ||mkdir -p $path
    done
}
CFBI_ungzip(){
    # ungzip fastq
    fastq_backup_wp=$1
    fqseq=${fastq_backup_wp}/fqseq
    memkdir $fqseq 
    ls ${fastq_backup_wp}/fqlink/*_R1.fastq.gz|cut -f1 -d.|parallel -j 3 "gzip -d {}.fastq.gz -c >$fqseq/{/.}.fq" 
}
CFBI_trim(){
    # trim fastq
    Deepseq_batch_id=$1 #; Deepseq_batch_id="2020120" 
    memkdir ${fastq_backup_wp}/fqtrimmed
    for i in ${fastq_backup_wp}/fqseq/*R1*
    do
    u=`basename $i`
    perl ${CFBI_sh_path}/fastq_trimmed.pl -f $i -5 5 -3 45 -o ${fastq_backup_wp}/fqtrimmed/$u  &
    metc 5
    done
    wait
}
requirment(){
    bwa 0.7.17
    samtools 1.9
    python 3.7.6
    GNU parallel 20190422
    perl v5.26.2
    BioPerl v1.7.2
    bedtools v2.29.0
}
CFBI_work_flow_all(){
    ###### Mon Mar 20 13:36:37 CST 2023
    index_path=${work_path}/index  ## make a index in the workpath
    ref_txt=${index_path}/ref_${Deepseq_batch_id}.txt
    info_file=$index_path/${Deepseq_batch_id}_deepseq_sample_name_mapping.csv
    line_per_record="5"
    python ${CFBI_sh_path}/_CFBI_preparation.py -c "DeepSeq" -f Deepseq_prepare_ref_sgRNARegion_nickSite -a $ref_txt,$index_path,$Deepseq_batch_id,$line_per_record  # python 3.7.6
    ref_file=${index_path}/ref_${Deepseq_batch_id}.fa # generated by Deepseq_prepare_ref_sgRNARegion_nickSite 
    python ${CFBI_sh_path}/_CFBI_preparation.py -c "DeepSeq" -f construct_ref_Individual -a $ref_file,$info_file,$start_index,$end_index  # python 3.7.6
    # run_py Deepseq_prepare_ref_sgRNARegion_nickSite DeepSeq $ref_txt,$index_path,$Deepseq_batch_id,$line_per_record
    # run_py construct_ref_Individual DeepSeq $ref_file,$info_file,$start_index,$end_index
    CFBI_ungzip $fastq_backup_wp
    # echo "1"
    CFBI_trim $Deepseq_batch_id
    # echo "2"
    # bash ${project_path}/sh/DeepSeq_flow.sh $start_index $end_index $Deepseq_batch_id 
    bash ${CFBI_sh_path}/DeepSeq_flow_Individual_ref.sh $work_path $start_index $end_index $Deepseq_batch_id 
    nick_sites=${index_path}/nick_sites_${Deepseq_batch_id}
    scope=10
    bash ${CFBI_sh_path}/DeepSeq_flow_indel_NbpSur_v2.sh $work_path $start_index $end_index $Deepseq_batch_id $nick_sites $scope
}

Deepseq_batch_id=20240220 ## change this 
source_path=/data/bioind1/reads/2024/2024.03.01_293FT_FYH_FS_Nova6000 ## change this
project_path=/data/bioind1/gaobaoqing/DNA_Cas9_ChenJia/DNA_Cas9_ChenJia_20240220/CFBI_efficiency ## change this
work_path=${project_path}

start_index=1 ## change this
end_index=146 ## change this
CFBI_sh_path=/data/bioind1/yuanguohua/biotools/CFBI/src

## link  
fastq_backup_wp=${work_path}/backup 
fqlink_path=${fastq_backup_wp}/fqlink 
memkdir $fqlink_path
cd $source_path
ls */*combined*.gz|awk -F"_|-" '{sample_index0=$6;sample_index=(sample_index0-24352);print "ln -sf '$source_path'/"$0" '$fqlink_path'/'$Deepseq_batch_id'DeepSeq_"sample_index"_"$NF}' |bash  ## change this, specifical 24352


PERL5LIB=/data/bioind1/yuanguohua/biotools/CFBI/perl_lib/site_perl/5.26.2/x86_64-linux-thread-multi:/data/bioind1/yuanguohua/biotools/CFBI/perl_lib/site_perl/5.26.2:/data/bioind1/yuanguohua/biotools/CFBI/perl_lib/5.26.2/x86_64-linux-thread-multi:/data/bioind1/yuanguohua/biotools/CFBI/perl_lib/5.26.2
export PERL5LIB

CFBI_work_flow_all
